### ISSUE TITLE
Photo gallery

### ISSUE THREAD

**Issue by roelofr** [gumbo-millennium/website#283]
# What's requested

We want to see photo albums separately from Facebook, since, well, fuck Facebook.

## TODO

- [x] Add album and photo model
- [x] Allow one-by-one uploads
- [x] Strip EXIF data
- [x] Allow bulk uploads via zip files
- [x] Allow bulk uploads via multi-select uploads
- [x] Allow browsing albums
- [x] Allow browsing photos
- [x] Allow marking albums as member-only
- [x] Allow marking albums as public
- [ ] Allow downloading of HQ images
- [ ] Allow downloading entire albums

## Designs

Something like this?

![image](https://user-images.githubusercontent.com/1771026/139100654-96b1c2c2-e54c-4087-8ab9-2fc0e0a64e0e.png)

**Comment by roelofr** [comment]
Models seem to work in v1, one error after creating a photo though:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'photo_albums.album_id' in 'where clause' (SQL: select * from `photo_albums` where `photo_albums`.`album_id` = 1 limit 1)

**Comment by roelofr** [comment]
First version is live, now to add more features.
