### ISSUE TITLE
Improve the "minisites"

### ISSUE THREAD

**Issue by roelofr** [gumbo-millennium/website#379]
Minisites are used for special events, like our introduction, LHW and the lustrums.

Currently, only the Lustrum site has special treatment, but we want to expand that to support all three custom sites, to allow groups to easily manage those websites and customize them, whilst also tying them into the Gumbo-site ecosystem.

Minisites only have support for a few routes, and are quick to forward users back to the Gumbo website.

## To-do list

- [x] Refactor Lustrum site to minisites
- [x] Extend minisites
- [x] Update nginx to point to Gumbo site, deprecating the old sites
- [ ] Add custom UI for Intro to allow signing up
- [ ] Add custom UI for LHW to allow enrolling

**Comment by roelofr** [comment]
Accidentally closed
